# -*- coding: utf-8 -*-
"""data wrangling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYApNINs4TFUfkZGY2OHLit9aFd_I8mJ
"""



import pandas as pd

df=pd.read_csv("ex.csv")

df

df=pd.read_csv("ex6.csv")

df

chunker=pd.read_csv("ex6.csv",chunksize=1000)

chunker

tot=pd.Series([],dtype='int64')
for piece in chunker:
  tot=tot.add(piece['key'].value_counts(),fill_value=0)

print(tot)

type(df)

df.to_csv("out.csv")

df

#to read data from csv file directly

import csv
data=open("ex6.csv")
d=csv.reader(data)

d

for i in d:
  print(i)

f=open("ex7.csv")
read=csv.reader(f)
for i in read:
  print(i)

i

with open("ex7.csv") as m:
  l=list(csv.reader(m))

l

l

l1=[1,2,3]
l2=['a','b','c']
re=list(zip(l1,l2))

re

for i in re:
  print(i)

i[0]

header,value= l[0],l[1:]

dicte={h:v for h,v in zip(header,zip(*value))}

header

dicte

#to read data from json

import json

obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}"""

import json
res = json.loads(obj)
res

a=json.dumps(res)

a

res['name']='thrus'

res

#to read data from html

tab=pd.read_html("https://www.w3schools.com/html/html_tables.asp")

tab

type(tab)

tabl=tab[0]

tabl

type(tabl)

tabl.columns

tab.columns

#to read the data from html file

data=pd.read_html("bank.html")

data

tab=data[0]

tab

tab.dtypes

#to convert the column 'closing date from string date_time object

clo=pd.to_datetime(tab['Closing Date'])

type(clo)

clo

clo.dt.year.value_counts()

p=clo.dt.month.value_counts()

p.sort_index()

clo.dt.date.value_counts().sort_index()

#to read data from xml

from lxml import objectify

path=
with open() as f:

