# -*- coding: utf-8 -*-
"""matplotlib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aV7gzGFgikfBdAD_xjN65EJu9O8ZeFLw
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

fig=plt.figure()

ax=fig.add_subplot(2,2,1)

ax

fig

ax.plot(np.arange(10),np.arange(10))
ax.plot(np.arange(20),np.arange(20))
ax.set_title("random")
ax.set_xlabel("x")
ax.set_ylabel('y')
plt.show()

ax.legend()

plt.show()

fig=plt.figure()

ax1=fig.add_subplot(2,3,1)

a=[1,2,10,30]
bins=10
ax1.hist(a,bins,color='r')
ax1.set_title('histogram')
ax1.set_xlabel('a')
ax1.set_ylabel('values')
plt.show()

x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = x**2

# Creating a figure
fig = plt.figure()

# Line plot
ax1 = fig.add_subplot(2, 3, 6)
ax1.plot(x, y1, label='sin(x)')
ax1.plot(x, y2, label='cos(x)')
ax1.set_title('Line Plot')
ax1.set_xlabel('x-axis')
ax1.set_ylabel('y-axis')
ax1.legend()

# Scatter plot
ax2 = fig.add_subplot(2, 3, 3)
ax2.scatter(x, y1, label='sin(x)', color='r', marker='o')
ax2.scatter(x, y2, label='cos(x)', color='b', marker='x')
ax2.set_title('Scatter Plot')
ax2.set_xlabel('x-axis')
ax2.set_ylabel('y-axis')
ax2.legend()

# Bar plot
ax3 = fig.add_subplot(2, 3, 2)
bar_labels = ['A', 'B', 'C', 'D', 'E']
bar_values = [3, 5, 7, 9, 6]
ax3.bar(bar_labels, bar_values, color='g', alpha=0.5)
ax3.set_title('Bar Plot')
ax3.set_xlabel('Categories')
ax3.set_ylabel('Values')

# Histogram
ax4 = fig.add_subplot(2, 3, 1)
data = np.random.randn(1000)
ax4.hist(data, bins=30, color='purple', alpha=0.7, edgecolor='black')
ax4.set_title('Histogram')
ax4.set_xlabel('Bins')
ax4.set_ylabel('Frequency')
a=[1,23,124,12,12]
b=['a','b','c','d','e']
ax5=fig.add_subplot(2,3,4)
ax5.bar(b,a)
plt.tight_layout()
plt.show()

fig

fig=plt.figure()
ax1=fig.add_subplot(2,2,2)
a=[100,234,124,120,129]
b=['a','b','c','d','e']
ax1.plot(b,a)
plt.tight_layout()
plt.show()

# Load an example dataset
iris = sns.load_dataset("iris")

# Data for the plots
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
data = pd.DataFrame({'x': x, 'sin(x)': y1, 'cos(x)': y2})

# Create a figure and a 2x2 grid
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

# Line plot
sns.lineplot(data=data, ax=axes[0, 0])
axes[0, 0].set_title("Line Plot")

# Scatter plot
sns.scatterplot(data=iris, x="sepal_length", y="sepal_width", hue="species", style="species", ax=axes[0, 1])
axes[0, 1].set_title("Scatter Plot")

# Bar plot
titanic = sns.load_dataset("titanic")
print(titanic.columns)
sns.barplot(data=titanic, x="class", y="fare", hue="survived", ax=axes[1, 0])
axes[1, 0].set_title("Bar Plot")

# Histogram (distplot in Seaborn is deprecated, so use histplot instead)
sns.histplot(data=iris, x="petal_length", kde=True, color='purple', ax=axes[1, 1])
axes[1, 1].set_title("Histogram")

# Adjusting the layout and displaying the plots
plt.tight_layout()
plt.show()

iris=sns.load_dataset('iris')

iris.columns

fig=plt.figure()
ax1=fig.add_subplot(2,2,1)

data=pd.read_csv("monthly_sales.csv")

data=pd.read_csv('monthly_sales.csv')

data

fig=plt.figure(figsize=(7,7))
#lineplot
ax1=fig.add_subplot(2,2,1)
ax1.plot(data['sales'],data['expenses'],color='r')
ax1.set_title('lineplot')
ax1.set_xlabel('sales')
ax1.set_ylabel('expenses')
#barplot
ax2=fig.add_subplot(2,2,2)
ax2.bar(data['customers'],data['sales'],color='b')
ax2.set_title('bar plot')
ax2.set_ylabel('sales')
ax2.set_xlabel('customers')
#scatterplot
ax3=fig.add_subplot(2,2,3)
ax3.scatter(data['expenses'],data['profit'],color='b')
ax3.set_title('scatter plot')
ax3.set_ylabel('expenses')
ax3.set_xlabel('profit')
#histplot
ax4=fig.add_subplot(2,2,4)
bins=10
ax4.hist(data['sales'],bins,color='brown')
ax4.set_title('hist plot')
ax4.set_ylabel('bins')
ax4.set_xlabel('sales')
plt.tight_layout()
plt.show()

sns.lineplot(data)

sns.barplot(data)

sns.pairplot(data)

