# -*- coding: utf-8 -*-
"""seaborn2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EWKn0nvl_MIHO-D-Aa46pXs3oIlkGSON
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Load example datasets
iris = sns.load_dataset("iris")
titanic = sns.load_dataset("titanic")


tips = sns.load_dataset("tips")
penguins = sns.load_dataset("penguins")

# Create a figure and a 2x2 grid
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

# Catplot (formerly factorplot)
sns.catplot(data=titanic, x="class", y="age", hue="survived", kind="box", ax=axes[0, 0])
axes[0, 0].set_title("Catplot (Boxplot)")
#plt.close(2)  # Catplot creates an extra figure, close it to keep only the main figure

# Pair plot
sns.pairplot(data=penguins,hue='species')
axes[0, 1].set_title("Pair Plot")

# Histplot (replacement for distplot)
sns.histplot(data=tips, x="total_bill", kde=True, ax=axes[1, 0])
axes[1, 0].set_title("Histplot (with KDE)")

# Regplot
sns.regplot(data=tips, x="total_bill", y="tip", ax=axes[1, 1])
axes[1, 1].set_title("Regplot")

# Adjusting the layout and displaying the plots
plt.tight_layout()
plt.show()